services:
  postgres:
    image: postgres:16
    container_name: trainee_wallet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trainee_wallet
    ports:
      - "5432:5432"
    volumes:
      - trainee_wallet_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trainee_wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  trainee_wallet_pgdata:
